stages:
- build-test
- deploy

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_REGISTRY: "nexus.informatik.haw-hamburg.de"
  SERVIE_NAME: "gis-data-svc"
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_COMMIT_REF_NAME"

build-and-test:
  stage: build-test
  image: $DOCKER_REGISTRY/maven:3-jdk-8-alpine
  script:
  - mvn clean package
  artifacts:
    paths:
    - ./target/*.jar
  tags:
    - k8s

deploy:
  stage: deploy
  services:
    - $DOCKER_REGISTRY/docker:stable-dind
  only:
    - master
  script:
    - docker login -u $NEXUS_USER -p $NEXUS_PW $DOCKER_REGISTRY
    - docker build -t $SERVIE_NAME:latest .
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:$CI_PIPELINE_ID
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:latest
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:$CI_COMMIT_SHA
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:$CI_PIPELINE_ID
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:latest
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:$CI_COMMIT_SHA
  tags:
    - k8s
