stages:
- build-test
- deploy

variables:
  SERVIE_NAME: "gis-data-svc"
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_REGISTRY: "nexus.informatik.haw-hamburg.de"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  untracked: true

buildAndTest:
  stage: build-test
  image: $DOCKER_REGISTRY/mars/maven-gdal
  script:
  - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
    - ./target/*.jar
  tags:
    - k8s

deployStable:
  stage: deploy
  services:
    - $DOCKER_REGISTRY/docker:stable-dind
  only:
    - master
  script:
    - docker login -u $NEXUS_USER -p $NEXUS_PW $DOCKER_REGISTRY
    - docker build -t $SERVIE_NAME:latest .
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:latest
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:$CI_PIPELINE_ID
    - docker tag $SERVIE_NAME:latest $DOCKER_REGISTRY/$SERVIE_NAME:$CI_COMMIT_SHA
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:latest
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:$CI_PIPELINE_ID
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:$CI_COMMIT_SHA
  tags:
    - k8s

deployBeta:
  stage: deploy
  services:
    - $DOCKER_REGISTRY/docker:stable-dind
  except:
    - master
  script:
    - docker login -u $NEXUS_USER -p $NEXUS_PW $DOCKER_REGISTRY
    - docker build -t $SERVIE_NAME:beta .
    - docker tag $SERVIE_NAME:beta $DOCKER_REGISTRY/$SERVIE_NAME:beta
    - docker push $DOCKER_REGISTRY/$SERVIE_NAME:beta
  tags:
    - k8s
