FROM artifactory.mars.haw-hamburg.de:5000/java:8
ADD target/gis-import-*.jar /target/
RUN ln -s /target/gis-import-*.jar /app.jar
EXPOSE 8080 8000
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-Xdebug","-Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=8000","-jar","/app.jar"]
