FROM nexus.informatik.haw-hamburg.de/openjdk:8-jre-alpine

RUN apk add --no-cache gdal --repository http://nl.alpinelinux.org/alpine/edge/testing

ADD target/gis-data-svc-*.jar /target/
RUN ln -s /target/gis-data-svc-*.jar /app.jar

EXPOSE 8080 8000

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-Xdebug","-Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=8000","-jar","/app.jar"]
