package org.mars_group.gisimport.web;

import org.mars_group.gisimport.exceptions.GisImportException;
import org.mars_group.gisimport.exceptions.GisValidationException;
import org.mars_group.gisimport.service.ImportService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;

@RestController
class FileController {

    private final ImportService importService;

    @Autowired
    public FileController(ImportService importService) {
        this.importService = importService;
    }

    /**
     * Import Geo files.
     *
     * @param dataId   generated by file-web
     * @param filename the name of the file, the user uploaded
     * @return status message
     */
    @ResponseBody
    @RequestMapping(method = RequestMethod.POST, value = "/gis")
    public ResponseEntity<String> postFile(@RequestParam String dataId,
                                           @RequestParam String title,
                                           @RequestParam String filename) {
        try {
            importService.downloadFile(dataId, filename);
            importService.startImport(title);

        } catch (GisImportException | IOException | GisValidationException e) {
            importService.setImportToFailed();
            e.printStackTrace();
            System.out.println(title + ": Import failed!");

            return new ResponseEntity<>(e.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);

        } finally {
            importService.deleteDirectoryOnDisk();
        }

        return new ResponseEntity<>("Import successful!", HttpStatus.CREATED);
    }

}
